[package]
name = "bcradio"
version = "0.8.0"
edition = "2021"

[profile.release]
debug = false
strip = "symbols"
lto = "fat"
codegen-units = 1

[features]


[dependencies]
anyhow = { version = "1.0.80" }
async-channel = { version = "2.2.0" }
async-std = { version = "1.12.0" }
async-trait = { version = "0.1.77" }
chrono = { version = "0.4.34"}
clap = { version = "4.5.1", features = ["derive"] }
colored = { version = "2.1.0" }
cpal = { version = "0.15.2", features = ["asio"] }
crossbeam = { version = "0.8.4" }
crossbeam-channel = { version = "0.5.11" }
crossbeam-utils = { version = "0.8.19" }
crossterm = { version = "0.27.0" }
futures = { version = "0.3.30" }
indicatif = { version = "0.17.8" }
inquire = { path = "external/inquire", version = "0.6.2" }
lazy_static = { version = "1.4.0" }
mp3-duration = { version = "0.1.10" }
once_cell = { version = "1.19.0" }
ratatui = { version = "0.26.0" }
reqwest = { version = "0.11.23", default-features = false, features = ["trust-dns", "blocking", "json", "stream", "gzip", "rustls-tls-native-roots"] }
rodio = { version = "0.17.3", features = ["symphonia", "symphonia-mp3" ] }
scraper = { version = "0.18.1" }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = { version = "1.0.112" }
symphonia = { version = "0.5.3" }
tokio = { version = "1.35.1", features = ["full"] }
tui-textarea = { version = "0.4.0" }
url = { version = "2.5.0"}
ctrlc = { version = "3.4.2" }
thiserror = { version = "1.0.56" }
curl = { version = "0.4.44", features = ["http2"] }
simd-json = { version = "0.13.8" }
bytes = { version = "1.5.0" }
flate2 = { version = "1.0.28" }
regex = "1.10.3"
chrono-tz = { version = "0.8.5" }
viu = { path = "external/viu", version = "1.5.0" }
viuer = { version = "0.7.1" }
itertools = "0.12.1"

[dev-dependencies]
env_logger = { version = "0.10.1" }
actix-web = { version = "4.4.1" }
actix-web-lab = { version = "0.20.1" }
actix-session = { version = "0.8.0", features = ["cookie-session"] }
actix-files = { version = "0.6.2" }
actix-rt = { version = "2.9.0" }
actix-http = { version = "3.5.1" }
serde_derive = { version = "1.0.194" }


[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52.0" }
sysinfo = { version = "0.30.0" }

[patch.crates-io]
cpal = { git = "https://github.com/RustAudio/cpal.git", branch = "master", commit = "f51589c" }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2.148" }

