[package]
name = "bcradio"
version = "0.2.0"
edition = "2021"

[profile.release]
debug = false
strip = "symbols"
lto = "fat"
codegen-units = 1

[features]


[dependencies]
anyhow = { version = "1.0.76" }
async-channel = { version = "2.1.0" }
async-std = { version = "1.12.0" }
async-stream = { version = "0.3.5" }
async-trait = { version = "0.1.75" }
chrono = { version = "0.4.31"}
clap = { version = "4.4.11", features = ["derive"] }
colored = { version = "2.1.0" }
console = { version = "0.15.7" }
cpal = { version = "0.15.2", features = ["asio"] }
crossbeam = { version = "0.8.2" }
crossbeam-channel = { version = "0.5.9" }
crossbeam-utils = { version = "0.8.17" }
crossterm = { version = "0.27.0" }
flume = { version = "0.11.0" }
futures = { version = "0.3.29" }
http = { version = "1.0.0" }
indicatif = { version = "0.17.7" }
inquire = { version = "0.6.2" }
lazy_static = { version = "1.4.0" }
lock_api = { version = "0.4.11" }
minimp3 = { package = "minimp3_fixed", version = "0.5.4", features = ["async_tokio"] }
minimp3-sys = { version = "0.3.2" }
mp3-duration = { version = "0.1.10" }
once_cell = { version = "1.19.0" }
rand = { version = "0.8.5" }
ratatui = { version = "0.25.0" }
reqwest = { version = "0.11.23", default-features = false, features = ["trust-dns", "blocking", "json", "stream", "gzip", "rustls-tls-native-roots"] }
rodio = { version = "0.17.3" }
scraper = { version = "0.18.1" }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = { version = "1.0.108" }
slice-ring-buffer = { version = "0.3.3" }
symphonia = { version = "0.5.3" }
tokio = { version = "1.35.1", features = ["full"] }
tokio-scoped = { version = "0.2.0" }
tui-textarea = { version = "0.4.0" }
url = { version = "2.5.0"}
ctrlc = { version = "3.4.1" }
thiserror = "1.0.51"
curl = { version = "0.4.44" }
async-curl = { version = "0.2.4" }
simd-json = "0.13.4"
rev_buf_reader = "0.3.0"
bytes = "1.5.0"
flate2 = "1.0.28"
futures-core = "0.3.29"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52.0" }
sysinfo = { version = "0.30.0" }

[patch.crates-io]
cpal = { git = "https://github.com/RustAudio/cpal.git", branch = "master", commit = "f51589c" }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2.148" }

