[target.x86_64-unknown-linux-gnu]
dockerfile = "./docker/Dockerfile_x86_64-unknown-linux-gnu"
[target.x86_64-unknown-linux-musl]
dockerfile = "./docker/Dockerfile_x86_64-unknown-linux-musl"
[target.aarch64-unknown-linux-gnu]
dockerfile = "./docker/Dockerfile_aarch64-unknown-linux-gnu"
[target.aarch64-unknown-linux-musl]
dockerfile = "./docker/Dockerfile_aarch64-unknown-linux-musl"
[target.armv7-unknown-linux-gnueabi]
dockerfile = "./docker/Dockerfile_armv7-unknown-linux-gnueabi"
[target.armv7-unknown-linux-musleabihf]
dockerfile = "./docker/Dockerfile_armv7-unknown-linux-musleabihf"
