FROM ghcr.io/cross-rs/x86_64-unknown-linux-musl:main

RUN apt update
RUN apt-get install -y wget pkg-config bzip2 make automake libtool
ENV CC=x86_64-linux-musl-gcc
RUN wget http://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.11.tar.bz2 && tar xf alsa-lib-1.2.11.tar.bz2 \
&& cd alsa-lib-1.2.11 && ./configure --enable-shared=yes --enable-static=no --with-pic --host=x86_64-linux-musl --prefix=/usr  \
&& make -j$(nproc) && make install

ENV PKG_CONFIG_PATH=/usr/lib/pkgconfig
ENV PKG_CONFIG_LIBDIR=/usr/lib
ENV PKG_CONFIG_ALLOW_CROSS=1
ENV RUSTFLAGS='-C target-feature=-crt-static'