name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest  , target: x86_64-unknown-linux-gnu       , cross: true    , extension: ""   }
          - { os: ubuntu-latest  , target: x86_64-unknown-linux-musl      , cross: true    , extension: ""   }
          - { os: ubuntu-latest  , target: armv7-unknown-linux-gnueabi    , cross: false   , extension: ""   }
          - { os: ubuntu-latest  , target: armv7-unknown-linux-musleabihf , cross: false   , extension: ""   }
          - { os: ubuntu-latest  , target: aarch64-unknown-linux-gnu      , cross: false   , extension: ""   }
          - { os: ubuntu-latest  , target: aarch64-unknown-linux-musl     , cross: false   , extension: ""   }
          - { os: macos-latest   , target: x86_64-apple-darwin            , cross: false   , extension: ""   }
          - { os: macos-latest   , target: aarch64-apple-darwin           , cross: false   , extension: ""   }
          - { os: windows-latest , target: x86_64-pc-windows-msvc         , cross: false   , extension: .exe }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract crate information
        shell: bash
        run: |
          echo "PROJECT_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' Cargo.toml | head -n1)" >> $GITHUB_ENV
      - name: Build
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          force-use-cross: ${{ matrix.job.cross }}
          target: ${{ matrix.job.target }}
          args: --release
          strip: true
      - name: Rename artifacts
        shell: bash
        run: |
          mv target/${{ matrix.job.target }}/release/${{ env.PROJECT_NAME }}{,-${{ github.ref_name }}-${{ matrix.job.target }}${{ matrix.job.extension }}}

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/${{ matrix.job.target }}/release/${{ env.PROJECT_NAME }}-${{ github.ref_name }}-${{ matrix.job.target }}${{ matrix.job.extension }}